### PR TITLE
Rename "Snakes" repo to "pipes.c"

### PR DESCRIPTION
**Pull request by StefansM**
Merge this once I've renamed the repository.

### CODE REVIEW

**Comment by livibetter** [comment]
@StefansM I think it's the JSON needs to be edited and to regenerate HTML with it (don't know using what), but I could be wrong.

@Foggalong we need docs, right now, you are the only one how exactly this gh-pages thing works.

----

I like we put histories of projects together, but it should be only significant ones, this renaming counts as one.  Frankly, I would also like each project to maintain their own section of slightly detailed history in their README or HISTORY file.

**Comment by livibetter** [comment]
ref: pipeseroni/Snakes#4

**Comment by StefansM** [comment]
@livibetter Ah-ha. I thought it might be some metadata automagically generated by GitHub, but it looks like it was generated by GitHub's [Automatic Page Generator](https://github.com/blog/1081-instantly-beautiful-project-pages). As far as I can tell, the APG no longer exists. Editing the HTML manually as per this PR would be a quick workaround, but we might wish to move to something like Jekyll.

**Comment by livibetter** [comment]
@StefansM Clearly, you know much more than I do.

We can still merge this (and likely would do just so at the moment), and open an issue for migrating to Jekyll, but we would also have to do on all repos as they all were made with this APG.  I think we might just axe all those and put everything here.

I've been thinking about this gh-pages web stuff, it surely has its advantage, because we would have the whole browser to display whatever we want.  But if we don't have a dedicate people, which we do, but only one, updating could be a slight issue.

As current information displayed on the website, I am kind of feeling that a simple README would do just fine, perhaps even better in terms of maintainability, because we all know how to edit a README and we can make it pretty enough inside the GitHub's README display.

**Pull request merged**
